version: 2.1
commands:
  buildgralde:
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: gradle test
      
      - run: gradle jacocoTestReport
      - run: bash <(curl -s https://codecov.io/bash)
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo
    steps:
          - buildgralde